const courses = [
  {
    courseCode: "CSC511",
    courseTitle: "Design and Analysis of Algorithm",
    level: "500",
    students: [
      { idNumber: "csc-15u-3338", score: null, sat: false },
      { idNumber: "csc-15u-3234", score: null, sat: false },
      { idNumber: "csc-15u-2834", score: null, sat: false },
      { idNumber: "csc-15u-4534", score: null, sat: false },
      { idNumber: "csc-15u-3323", score: null, sat: false },
      { idNumber: "csc-15u-2896", score: null, sat: false },
      { idNumber: "csc-15u-3301", score: null, sat: false },
      { idNumber: "csc-15u-3339", score: null, sat: false },
      { idNumber: "csc-15u-3233", score: null, sat: false },
      { idNumber: "csc-15u-3243", score: null, sat: false },
      { idNumber: "csc-15u-4434", score: null, sat: false },
      { idNumber: "csc-15u-2287", score: null, sat: false },
      { idNumber: "csc-15u-2789", score: null, sat: false },
      { idNumber: "csc-15u-3456", score: null, sat: false },
      { idNumber: "csc-15u-3356", score: null, sat: false },
    ],
  },
  // {
  //   courseCode: "CSC503",
  //   courseTitle: "Software Engineering",
  //   level: "500",
  //   students: [
  //     { idNumber: "csc-15u-3234", score: null, sat: false },
  //     { idNumber: "csc-15u-3338", score: null, sat: false },
  //     { idNumber: "csc-15u-2834", score: null, sat: false },
  //     { idNumber: "csc-15u-4534", score: null, sat: false },
  //     { idNumber: "csc-15u-3323", score: null, sat: false },
  //     { idNumber: "csc-15u-2896", score: null, sat: false },
  //     { idNumber: "csc-15u-3301", score: null, sat: false },
  //     { idNumber: "csc-15u-3339", score: null, sat: false },
  //     { idNumber: "csc-15u-3233", score: null, sat: false },
  //     { idNumber: "csc-15u-3243", score: null, sat: false },
  //     { idNumber: "csc-15u-4434", score: null, sat: false },
  //     { idNumber: "csc-15u-2287", score: null, sat: false },
  //     { idNumber: "csc-15u-2789", score: null, sat: false },
  //     { idNumber: "csc-15u-3456", score: null, sat: false },
  //     { idNumber: "csc-15u-3356", score: null, sat: false },
  //   ],
  // },
];

module.exports = courses;
